name: Space Invaders Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Space Invaders
        uses: czl9707/gh-space-shooter@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
